/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Daniel
 */
public class MenuBotonMostrar extends javax.swing.JPanel {

    /**
     * Creates new form MenuBotonIngresar
     */
    public MenuBotonMostrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRefrescarMostrar = new javax.swing.JButton();
        btnModificarMostrar = new javax.swing.JButton();
        btnLimpiarMostrar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(100, 270));

        btnRefrescarMostrar.setText("Refrescar");
        btnRefrescarMostrar.setActionCommand("Refrescar");
        btnRefrescarMostrar.setPreferredSize(new java.awt.Dimension(90, 29));
        btnRefrescarMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarMostrarActionPerformed(evt);
            }
        });

        btnModificarMostrar.setText("Modificar");
        btnModificarMostrar.setPreferredSize(new java.awt.Dimension(90, 29));
        btnModificarMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMostrarActionPerformed(evt);
            }
        });

        btnLimpiarMostrar.setText("Limpiar");
        btnLimpiarMostrar.setPreferredSize(new java.awt.Dimension(90, 29));
        btnLimpiarMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRefrescarMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnModificarMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnLimpiarMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnRefrescarMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnModificarMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnLimpiarMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefrescarMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefrescarMostrarActionPerformed

    private void btnModificarMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMostrarActionPerformed

    private void btnLimpiarMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLimpiarMostrar;
    public javax.swing.JButton btnModificarMostrar;
    public javax.swing.JButton btnRefrescarMostrar;
    // End of variables declaration//GEN-END:variables
}
